import {DM_Serif_Display, Playfair_Display} from 'next/font/google';

import './globals.css';
import ContactBanner from '@/components/contact/ContactBanner';
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';

const dm_serif_display = DM_Serif_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm_serif_display',
  weight: '400',
});
const playfair_display = Playfair_Display({subsets: ['latin'], display: 'swap', variable: '--font-playfair_display'});

export const metadata = {
  title: 'CARA',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/trajan-pro?styles=17675,17676" rel="stylesheet" />
      </head>
      <body className={` ${dm_serif_display.variable} ${playfair_display.variable} min-h-screen`}>
        <Header />
        {/* <div className="pt-[192px]">
        </div> */}
        <div className="flex-1 w-full h-[cacl(100vh-8.875rem)] pt-[95px] lg:pt-[142px]">{children}</div>
        <ContactBanner />
        <Footer />
      </body>
    </html>
  );
}
